In [1]:
import numpy as np

In [ ]:
X = np.array([[1, 1], [3, 1], [1, 4], [2, 4], [3, 3], [5, 1]])
y = np.array([0, 0, 0, 1, 1, 1])

In [3]:
X = np.loadtxt("data.txt", delimiter=",")
y = np.loadtxt("target.txt")



In [4]:
X[:5]

array([[ 1.1107, -2.1079,  1.    ],
       [-0.5498,  0.0943,  1.    ],
       [-0.0382,  1.8829,  1.    ],
       [ 0.0555, -0.6139,  1.    ],
       [ 0.587 , -1.2067,  1.    ]])

In [5]:
X = X[:,:2]

In [6]:
X[:5]

array([[ 1.1107, -2.1079],
       [-0.5498,  0.0943],
       [-0.0382,  1.8829],
       [ 0.0555, -0.6139],
       [ 0.587 , -1.2067]])

In [7]:
k = 1

In [8]:
eps = 1e-8

In [9]:
X_train = X

In [10]:
y_train = y

In [11]:
num_loop = 0

In [12]:
X_test = X[:,:2]

In [14]:
X_test[:5]

array([[ 1.1107, -2.1079],
       [-0.5498,  0.0943],
       [-0.0382,  1.8829],
       [ 0.0555, -0.6139],
       [ 0.587 , -1.2067]])

to find (X_train - Xtest)^2

(a-b)^2 = a^2 - 2a (dot) b + b^2

In [15]:
X_test_squared = np.sum(X_test ** 2, axis=1, keepdims=True)

In [17]:
X_test_squared[:5]

array([[5.6768969 ],
       [0.31117253],
       [3.54677165],
       [0.37995346],
       [1.80069389]])

In [22]:
X_test_squared.shape

(90, 1)

In [18]:
X_train_squared = np.sum(X_train ** 2, axis=1, keepdims=True)

In [20]:
X_train_squared[:5]

array([[5.6768969 ],
       [0.31117253],
       [3.54677165],
       [0.37995346],
       [1.80069389]])

In [23]:
X_train_squared.shape

(90, 1)

In [21]:
two_X_test_X_train = np.dot(X_test, X_train.T) # 90x1 . 1x90 = 90x90


In [24]:
two_X_test_X_train

array([[ 5.6768969 , -0.80943783, -4.01139365, ...,  6.18317941,
         8.19093985,  6.68103606],
       [-0.80943783,  0.31117253,  0.19855983, ..., -1.27388536,
        -1.24097818, -1.00704342],
       [-4.01139365,  0.19855983,  3.54677165, ..., -3.62092216,
        -5.6484691 , -4.61711106],
       ...,
       [ 6.18317941, -1.27388536, -3.62092216, ...,  7.52061757,
         9.06786211,  7.38593844],
       [ 8.19093985, -1.24097818, -5.6484691 , ...,  9.06786211,
        11.84561905,  9.66008616],
       [ 6.68103606, -1.00704342, -4.61711106, ...,  7.38593844,
         9.66008616,  7.87792356]], shape=(90, 90))

In [27]:
distance = eps + X_test_squared - 2 * two_X_test_X_train + X_train_squared.T   # = (X_train - Xtest)^2

In [61]:
def train(X, y):
    X_train = X
    y_train = y

In [28]:
def compute_distance_vectorized( X_test):
        """
        Can be tricky to understand this, we utilize heavy
        vecotorization as well as numpy broadcasting.
        Idea: if we have two vectors a, b (two examples)
        and for vectors we can compute (a-b)^2 = a^2 - 2a (dot) b + b^2
        expanding on this and doing so for every vector lends to the 
        heavy vectorized formula for all examples at the same time.
        """
        X_test_squared = np.sum(X_test ** 2, axis=1, keepdims=True)
        X_train_squared = np.sum(X_train ** 2, axis=1, keepdims=True)
        two_X_test_X_train = np.dot(X_test, X_train.T)

        # (Taking sqrt is not necessary: min distance won't change since sqrt is monotone)
        return np.sqrt(
            eps + X_test_squared - 2 * two_X_test_X_train + X_train_squared.T
        )

In [ ]:
# X_test_squared = np.sum(X_test ** 2, axis=1, keepdims=True):
# Squares each element of X_test.
# Sums the squared elements along the rows (axis=1).
# Keeps the result as a 2D array with one column using keepdims=True.
# X_train_squared = np.sum(self.X_train ** 2, axis=1, keepdims=True):
# Squares each element of X_train.
# Sums the squared elements along the rows (axis=1).
# Keeps the result as a 2D array with one column using keepdims=True.
# two_X_test_X_train = np.dot(X_test, self.X_train.T):
# Computes the dot product of X_test and the transpose of X_train.
# This gives the matrix product of X_test and X_train, where each element is the dot product of a row in X_test and a row in X_train.
# return np.sqrt(self.eps + X_test_squared - 2 * two_X_test_X_train + X_train_squared.T):
# Computes the Euclidean distance between each row in X_test and each row in X_train using the formula: sqrt(a^2 - 2a(dot)b + b^2).
# self.eps is added to the result to avoid division by zero.
# The result is a matrix where each element is the Euclidean distance between a row in X_test and a row in X_train.

In [55]:
X_train

array([[ 1.1107, -2.1079],
       [-0.5498,  0.0943],
       [-0.0382,  1.8829],
       [ 0.0555, -0.6139],
       [ 0.587 , -1.2067],
       [ 0.5453,  0.2509],
       [-0.3927, -0.622 ],
       [-1.1905, -1.8785],
       [-0.424 ,  0.7772],
       [-0.7139,  1.5846],
       [-0.8883,  2.1408],
       [-0.6922,  0.0993],
       [ 1.435 ,  1.2334],
       [-0.7576,  0.7386],
       [-1.1144, -1.7059],
       [ 0.6612, -1.7296],
       [-2.1381, -0.06  ],
       [ 1.3857,  1.2178],
       [-1.4951,  0.0373],
       [ 0.8029,  0.9739],
       [ 1.5607,  1.5862],
       [ 0.8563, -1.4245],
       [ 0.0397, -1.3799],
       [ 1.2331,  1.7421],
       [-2.0015,  0.8355],
       [-0.3428, -0.478 ],
       [-0.8891,  1.2634],
       [ 0.3832, -0.1189],
       [ 0.4172,  1.0132],
       [-0.8695, -0.7947],
       [ 2.9737,  3.6438],
       [ 3.768 ,  1.8649],
       [ 0.1166,  0.9435],
       [ 0.6896,  3.916 ],
       [ 1.2234,  2.9899],
       [ 2.3009,  0.415 ],
       [ 3.7693,  3.8027],
 

In [56]:
X_test[0, :]

array([ 1.1107, -2.1079])

In [54]:
X_train - X_test[0, :] # for first row of test  numpy broadcast

array([[ 0.    ,  0.    ],
       [-1.6605,  2.2022],
       [-1.1489,  3.9908],
       [-1.0552,  1.494 ],
       [-0.5237,  0.9012],
       [-0.5654,  2.3588],
       [-1.5034,  1.4859],
       [-2.3012,  0.2294],
       [-1.5347,  2.8851],
       [-1.8246,  3.6925],
       [-1.999 ,  4.2487],
       [-1.8029,  2.2072],
       [ 0.3243,  3.3413],
       [-1.8683,  2.8465],
       [-2.2251,  0.402 ],
       [-0.4495,  0.3783],
       [-3.2488,  2.0479],
       [ 0.275 ,  3.3257],
       [-2.6058,  2.1452],
       [-0.3078,  3.0818],
       [ 0.45  ,  3.6941],
       [-0.2544,  0.6834],
       [-1.071 ,  0.728 ],
       [ 0.1224,  3.85  ],
       [-3.1122,  2.9434],
       [-1.4535,  1.6299],
       [-1.9998,  3.3713],
       [-0.7275,  1.989 ],
       [-0.6935,  3.1211],
       [-1.9802,  1.3132],
       [ 1.863 ,  5.7517],
       [ 2.6573,  3.9728],
       [-0.9941,  3.0514],
       [-0.4211,  6.0239],
       [ 0.1127,  5.0978],
       [ 1.1902,  2.5229],
       [ 2.6586,  5.9106],
 

In [57]:
def compute_distance_one_loop(X_test):
        """
        Much better than two-loops but not as fast as fully vectorized version.
        Utilize Numpy broadcasting in X_train - X_test[i,:]
        """
        num_test = X_test.shape[0]
        num_train = X_train.shape[0]
        distances = np.zeros((num_test, num_train))

        for i in range(num_test):
            # (Taking sqrt is not necessary: min distance won't change since sqrt is monotone)
            distances[i, :] = np.sqrt(
                eps + np.sum((X_train - X_test[i, :]) ** 2, axis=1)
            )

        return distances

In [59]:
(X_test[0, :] - X_train[0, :])

array([0., 0.])

In [58]:
def compute_distance_two_loops(X_test):
        """
        Inefficient naive implementation, use only
        as a way of understanding what kNN is doing
        """

        num_test = X_test.shape[0]
        num_train = X_train.shape[0]
        distances = np.zeros((num_test, num_train))

        for i in range(num_test):
            for j in range(num_train):
                # (Taking sqrt is not necessary: min distance won't change since sqrt is monotone)
                distances[i, j] = np.sqrt(
                    eps + np.sum((X_test[i, :] - X_train[j, :]) ** 2)
                )

        return distances

In [45]:
num_test = distance.shape[0]

In [46]:
num_test

90

In [31]:
y_pred = np.zeros(num_test)

In [32]:
y_pred 

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(90, 90))

In [33]:
y_indices = np.argsort(distance[0, :])# indexes after sorting the first row of distances

In [35]:
y_indices.shape

(90,)

In [34]:
y_indices # for first row of distances

array([ 0, 73, 74, 64, 72, 89, 78, 15, 60, 75, 21, 79, 61, 87, 81,  4, 71,
       88, 85, 86, 22, 77, 82, 84, 63, 83, 65, 69, 62,  3,  6, 27, 76, 25,
       14,  7, 29,  5, 70, 66,  1, 35, 11, 67, 68, 19, 28, 32,  8, 55, 46,
       17, 12, 18, 13, 48, 51, 20, 16, 23, 80, 26, 40,  9,  2, 58, 50, 24,
       41, 44, 10, 31, 59, 45, 34, 49, 56, 54, 57, 38, 53, 52, 37, 47, 42,
       33, 30, 43, 39, 36])

In [36]:
y_train[y_indices] # traget for first row of distances

array([1., 3., 3., 3., 3., 3., 3., 1., 3., 3., 1., 3., 3., 3., 3., 1., 3.,
       3., 3., 3., 1., 3., 3., 3., 3., 3., 3., 3., 3., 1., 1., 1., 3., 1.,
       1., 1., 1., 1., 3., 3., 1., 2., 1., 3., 3., 1., 1., 2., 1., 2., 2.,
       1., 1., 1., 1., 2., 2., 1., 1., 1., 3., 1., 2., 1., 1., 2., 2., 1.,
       2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.])

In [40]:
k_closest_classes = y_train[y_indices[:k]].astype(int)

In [42]:
k_closest_classes # for first row of distances

array([1])

In [ ]:
# np.bincount(k_closest_classes) is a NumPy function that counts the number of occurrences of each class label in the k_closest_classes array.
# How it works:
# np.bincount takes an array of non-negative integers as input.
# It returns an array where the i-th element represents the number of times the integer i appears in the input array.
# Example:
# Suppose k_closest_classes = [1, 0, 1, 2, 1, 0]. Then:

# Class label 0 appears 2 times.
# Class label 1 appears 3 times.
# Class label 2 appears 1 time.

In [41]:
np.bincount(k_closest_classes) # class 0 appears 0 times and class 1 appears 1 times

array([0, 1])

In [43]:
np.argmax(np.argmax(k_closest_classes)) # class 

np.int64(0)

In [47]:
for i in range(num_test):
    y_indices = np.argsort(distance[i, :])
    k_closest_classes = y_train[y_indices[: k]].astype(int)
    y_pred[i] = np.argmax(np.bincount(k_closest_classes))

In [48]:
y_indices # for last row

array([89, 74, 73, 78,  0, 64, 88, 72, 79, 75, 60, 87, 61, 71, 81, 15, 85,
       86, 77, 21, 83, 82, 63, 65, 84,  4, 69, 62, 22, 76,  3, 27, 70,  6,
       66, 25, 14,  7, 29,  5, 67, 35, 68,  1, 11, 19, 28, 46, 55, 32, 48,
       51, 17, 12,  8, 80, 18, 13, 20, 23, 16, 40, 26,  9,  2, 58, 50, 24,
       41, 44, 31, 10, 45, 56, 49, 59, 34, 54, 57, 52, 38, 37, 53, 47, 42,
       30, 39, 33, 43, 36])

In [49]:
k_closest_classes # for last row

array([3])

In [50]:
y_pred

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.],
       [3., 3., 3., ..., 3., 3., 3.]], shape=(90, 90))

In [52]:
y_pred[89] # for last row

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.])

In [53]:
def predict_labels( distances):
        num_test = distances.shape[0]
        y_pred = np.zeros(num_test)

        for i in range(num_test):
            y_indices = np.argsort(distances[i, :])
            k_closest_classes = y_train[y_indices[: k]].astype(int)
            y_pred[i] = np.argmax(np.bincount(k_closest_classes))

        return y_pred

In [60]:
def predict( X_test, num_loops=0):
        if num_loops == 0:
            distances = compute_distance_vectorized(X_test)

        elif num_loops == 1:
            distances = compute_distance_one_loop(X_test)

        else:
            distances = compute_distance_two_loops(X_test)

        return predict_labels(distances)

In [62]:
train(X, y)

In [63]:
predict(X, num_loops=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.])

In [64]:
predict(X, num_loops=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.])

In [65]:
predict(X, num_loops=2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.])